#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$repo_root/scripts/release-common.sh"

usage() {
  cat <<'EOF'
Usage: ./build.sh [--config FILE] [--spark-hosts HOST,...]

Builds the coordinator image locally and the Spark image natively over SSH on
the first configured Spark. It exports both release artifact sets to dist/
and distributes the Spark inference image to all configured Spark hosts.
Use --spark-hosts ostrich,dodo to build and distribute only on available hosts;
this does not change the four-rank serving topology.

Dirty checkouts get an automatic source manifest under .ds41rt-release/.
Keep source files unchanged during the build; local and remote inventories
are verified against that manifest. DS41RT_RELEASE_SOURCE_MANIFEST can supply
an existing manifest. Source archives without .git must also provide
DS41RT_RELEASE_ENGINE_REVISION (REVISION or REVISION-dirty-MANIFEST12).
EOF
}

config="$repo_root/ds41rt.config"
build_hosts_csv=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      config="${2:?$1 requires a configuration file}"
      shift 2
      ;;
    --spark-hosts)
      build_hosts_csv="${2:?--spark-hosts requires a comma-separated host list}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      release_die "unknown build argument: $1"
      ;;
  esac
done

release_load_config "$config"
release_select_build_hosts "$build_hosts_csv"
release_need docker
release_need ssh
release_need rsync
release_need sha256sum
release_need python3
release_need install

release_version="${COORDINATOR_DOCKER_INFERENCE##*:}"
spark_release_version="${SPARK_EXPERT_DOCKER_INFERENCE##*:}"
[[ "$release_version" != "$COORDINATOR_DOCKER_INFERENCE" &&
  "$release_version" =~ ^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$ ]] ||
  release_die "coordinator inference image must use a valid release tag"
[[ "$spark_release_version" == "$release_version" ]] ||
  release_die "coordinator and Spark inference image release tags must match"

prepare_pinned_source_dependencies() {
  local git_root=""
  if command -v git >/dev/null 2>&1; then
    git_root="$(git -C "$repo_root" rev-parse --show-toplevel 2>/dev/null || true)"
  fi

  if [[ -n "$git_root" &&
    "$(cd "$git_root" && pwd -P)" == "$(cd "$repo_root" && pwd -P)" ]]; then
    echo "== preparing pinned source dependencies =="
    git -C "$repo_root" submodule sync -- \
      third_party/sparkinfer third_party/xgrammar
    git -C "$repo_root" submodule update --init --checkout -- \
      third_party/sparkinfer third_party/xgrammar
    git -C "$repo_root/third_party/xgrammar" submodule sync -- \
      3rdparty/dlpack
    git -C "$repo_root/third_party/xgrammar" submodule update --init --checkout -- \
      3rdparty/dlpack
  fi

  [[ -f "$repo_root/third_party/sparkinfer/b12x/__init__.py" ]] ||
    release_die "SparkInfer source is missing; initialize third_party/sparkinfer"
  [[ -f "$repo_root/third_party/xgrammar/include/xgrammar/compiler.h" ]] ||
    release_die "XGrammar source is missing; initialize third_party/xgrammar"
  [[ -f "$repo_root/third_party/xgrammar/3rdparty/dlpack/include/dlpack/dlpack.h" ]] ||
    release_die "XGrammar DLPack source is missing; initialize third_party/xgrammar/3rdparty/dlpack"
}

prepare_pinned_source_dependencies

docker info >/dev/null 2>&1 || release_die "local Docker daemon is unavailable"
detected_engine_commit="$(git -C "$repo_root" rev-parse HEAD 2>/dev/null || true)"
engine_source_dirty=0
if [[ -n "$detected_engine_commit" &&
  -n "$(git -C "$repo_root" status --porcelain 2>/dev/null || true)" ]]; then
  engine_source_dirty=1
fi
source_manifest="${DS41RT_RELEASE_SOURCE_MANIFEST:-}"
source_manifest_sha256=""
if [[ -z "$source_manifest" ]] && ((engine_source_dirty)); then
  # Build provenance is generated by the build, not an extra manual prerequisite.
  # This directory is excluded from both the inventory and remote source sync.
  mkdir -p "$repo_root/.ds41rt-release/source-manifests"
  source_manifest="$(mktemp "$repo_root/.ds41rt-release/source-manifests/source.XXXXXXXX.sha256")"
  python3 "$repo_root/scripts/verify-release-source-manifest.py" \
    --source "$repo_root" --write "$source_manifest"
  echo "== recorded current checkout: $source_manifest =="
fi
if [[ -n "$source_manifest" ]]; then
  source_manifest="$(
    python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' \
      "$source_manifest"
  )"
  [[ -f "$source_manifest" ]] ||
    release_die "release source manifest not found: $source_manifest"
  source_manifest_sha256="$(sha256sum "$source_manifest" | awk '{print $1}')"
fi

verify_local_source_manifest() {
  [[ -n "$source_manifest" ]] || return 0
  local current_source_manifest_sha256
  current_source_manifest_sha256="$(
    sha256sum "$source_manifest" | awk '{print $1}'
  )"
  [[ "$current_source_manifest_sha256" == "$source_manifest_sha256" ]] ||
    release_die "release source manifest changed during the build"
  python3 "$repo_root/scripts/verify-release-source-manifest.py" \
    --source "$repo_root" \
    --manifest "$source_manifest" ||
    release_die "release source differs from $source_manifest"
}

verify_remote_source_manifest() {
  [[ -n "$source_manifest" ]] || return 0
  local current_source_manifest_sha256
  current_source_manifest_sha256="$(
    sha256sum "$source_manifest" | awk '{print $1}'
  )"
  [[ "$current_source_manifest_sha256" == "$source_manifest_sha256" ]] ||
    release_die "release source manifest changed during the build"
  local remote_dir_quoted
  printf -v remote_dir_quoted '%q' "$remote_dir"
  ssh -o BatchMode=yes "$seed_host" \
    "cd $remote_dir_quoted && python3 scripts/verify-release-source-manifest.py --source . --manifest -" \
    <"$source_manifest" ||
    release_die "$seed_host staged source differs from $source_manifest"
}

verify_local_source_manifest
sparkinfer_commit="$(
  python3 "$repo_root/scripts/verify-sparkinfer-source.py" \
    --source "$repo_root/third_party/sparkinfer" \
    --lock "$repo_root/third_party/sparkinfer.lock.json" \
    --print-revision
)"
python3 "$repo_root/scripts/verify-xgrammar-source.py" \
  --source "$repo_root/third_party/xgrammar" \
  --lock "$repo_root/third_party/xgrammar.lock.json"
engine_revision_override="${DS41RT_RELEASE_ENGINE_REVISION:-}"
if [[ -n "$engine_revision_override" ]]; then
  [[ "$engine_revision_override" =~ ^[0-9a-f]{40}(-dirty-[0-9a-f]{12})?$ ]] ||
    release_die "DS41RT_RELEASE_ENGINE_REVISION must be REVISION or REVISION-dirty-MANIFEST12"
  [[ -n "$source_manifest_sha256" ]] ||
    release_die "DS41RT_RELEASE_ENGINE_REVISION requires DS41RT_RELEASE_SOURCE_MANIFEST"
  engine_commit="$engine_revision_override"
elif [[ -z "$detected_engine_commit" ]]; then
  release_die "source snapshot has no Git metadata; set DS41RT_RELEASE_ENGINE_REVISION and DS41RT_RELEASE_SOURCE_MANIFEST"
elif ((engine_source_dirty)); then
  [[ -n "$source_manifest_sha256" ]] ||
    release_die "dirty release source requires DS41RT_RELEASE_SOURCE_MANIFEST"
  engine_commit="${detected_engine_commit}-dirty-${source_manifest_sha256:0:12}"
else
  engine_commit="$detected_engine_commit"
fi
if [[ "$engine_commit" == *-dirty-* ]]; then
  [[ -n "$source_manifest_sha256" ]] ||
    release_die "dirty engine revision requires DS41RT_RELEASE_SOURCE_MANIFEST"
  [[ "$engine_commit" == *"-dirty-${source_manifest_sha256:0:12}" ]] ||
    release_die "dirty engine revision suffix does not match the source manifest"
fi
release_source_label_args=()
if [[ -n "$source_manifest_sha256" ]]; then
  release_source_label_args+=(
    --label "io.ds41rt.source-manifest.sha256=$source_manifest_sha256"
  )
fi

hosts_csv="$(IFS=,; echo "${RELEASE_BUILD_HOSTS[*]}")"
seed_host="${RELEASE_BUILD_HOSTS[0]}"
remote_dir="${DS41RT_RELEASE_REMOTE_BUILD_DIR:-}"
artifact_dir="$repo_root/.ds41rt-release-image"

echo "== validating native Spark build hosts =="
for host in "${RELEASE_BUILD_HOSTS[@]}"; do
  ssh -o BatchMode=yes -o ConnectTimeout=10 "$host" bash -s <<'REMOTE'
set -euo pipefail
command -v docker >/dev/null
docker info >/dev/null
test "$(uname -m)" = "aarch64"
REMOTE
  echo "  $host: ssh/docker/aarch64 ready"
done

release_sync_program=rsync
if command -v rdmasync >/dev/null 2>&1 &&
  ssh -o BatchMode=yes "$seed_host" "command -v rdmasync >/dev/null 2>&1"; then
  release_sync_program=rdmasync
  echo "== using RDMA source/artifact synchronization =="
fi

release_sync() {
  if [[ "$release_sync_program" == rdmasync ]]; then
    rdmasync -a --rdma=required --rdma-show-config "$@"
  else
    rsync -a "$@"
  fi
}

if [[ -z "$remote_dir" ]]; then
  remote_dir="$(
    ssh -o BatchMode=yes "$seed_host" \
      'printf "%s/ds41rt-release-build" "$HOME"'
  )"
fi

local_free_kib="$(df -Pk "$repo_root" | awk 'NR==2 {print $4}')"
((local_free_kib >= 60 * 1024 * 1024)) || release_die "local build needs at least 60 GiB free"
remote_free_kib="$(
  ssh -o BatchMode=yes "$seed_host" bash -s <<'REMOTE'
df -Pk "$HOME" | awk 'NR == 2 { print $4 }'
REMOTE
)"
((remote_free_kib >= 60 * 1024 * 1024)) || release_die "$seed_host build needs at least 60 GiB free"

echo "== building coordinator development image: $COORDINATOR_DOCKER_DEV =="
docker build \
  --build-arg DS41RT_ROLE=coordinator \
  --build-arg CUDA_ARCH=120 \
  --build-arg TARGET_PLATFORM=linux/amd64 \
  --build-arg DS41RT_SPARKINFER_COMMIT="$sparkinfer_commit" \
  -f "$repo_root/docker/Dockerfile.dev" \
  -t "$COORDINATOR_DOCKER_DEV" \
  "$repo_root"

echo "== compiling coordinator release artifacts in GPU-enabled development container =="
mkdir -p "$artifact_dir"
docker run --rm \
  --gpus device=0 \
  --ipc=host \
  --ulimit memlock=-1:-1 \
  -e CUDA_VISIBLE_DEVICES=0 \
  -e NVIDIA_VISIBLE_DEVICES=0 \
  -v "$repo_root:/source:ro" \
  -v "$artifact_dir:/output" \
  "$COORDINATOR_DOCKER_DEV" \
  /source/scripts/build-release-artifacts.sh /source coordinator 120 /output

echo "== building coordinator inference image: $COORDINATOR_DOCKER_INFERENCE =="
docker build \
  "${release_source_label_args[@]}" \
  --build-arg DS41RT_ROLE=coordinator \
  --build-arg CUDA_ARCH=120 \
  --build-arg DS41RT_ENGINE_COMMIT="$engine_commit" \
  --build-arg DS41RT_SPARKINFER_COMMIT="$sparkinfer_commit" \
  --build-arg DS41RT_RELEASE_VERSION="$release_version" \
  -f "$repo_root/docker/Dockerfile.release" \
  -t "$COORDINATOR_DOCKER_INFERENCE" \
  "$repo_root"

echo "== staging native Spark build on $seed_host:$remote_dir =="
ssh -o BatchMode=yes "$seed_host" "mkdir -p '$remote_dir'"
release_sync --delete \
  --exclude '.git' \
  --exclude '.venv*/' \
  --exclude '.mypy_cache/' \
  --exclude '.pytest_cache/' \
  --exclude '.ruff_cache/' \
  --exclude '__pycache__/' \
  --exclude '*.pyc' \
  --exclude '*.pyo' \
  --exclude '.ds41rt-cache/' \
  --exclude '.ds41rt-release/' \
  --exclude '.ds41rt-release-image/' \
  --exclude '.ds41rt-wip/' \
  --exclude 'dist/' \
  --exclude 'rust/target/' \
  --exclude 'native/build*/' \
  "$repo_root/" "$seed_host:$remote_dir/"
# The broad staging sync protects excluded paths from deletion. Reconcile the
# pinned source separately so bytecode left by an earlier build cannot survive
# merely because it is now excluded.
release_sync --delete --delete-excluded \
  --exclude '.git' \
  --exclude '.venv*/' \
  --exclude '.mypy_cache/' \
  --exclude '.pytest_cache/' \
  --exclude '.ruff_cache/' \
  --exclude '__pycache__/' \
  --exclude '*.pyc' \
  --exclude '*.pyo' \
  "$repo_root/third_party/sparkinfer/" \
  "$seed_host:$remote_dir/third_party/sparkinfer/"
release_sync --delete --delete-excluded \
  --exclude '.git' \
  --exclude '__pycache__/' \
  --exclude '*.pyc' \
  --exclude '*.pyo' \
  "$repo_root/third_party/xgrammar/" \
  "$seed_host:$remote_dir/third_party/xgrammar/"
verify_remote_source_manifest

echo "== building Spark development and inference images natively on $seed_host =="
ssh -o BatchMode=yes "$seed_host" bash -s -- \
  "$remote_dir" "$SPARK_EXPERT_DOCKER_DEV" "$SPARK_EXPERT_DOCKER_INFERENCE" \
  "$engine_commit" "$sparkinfer_commit" "$release_version" \
  "$EXL3_PAIRED_TP4" "$source_manifest_sha256" <<'REMOTE'
set -euo pipefail
remote_dir="$1"
dev_image="$2"
inference_image="$3"
engine_commit="$4"
sparkinfer_commit="$5"
release_version="$6"
exl3_paired_tp4="$7"
# SSH reconstructs a shell command and can omit an empty trailing argument.
source_manifest_sha256="${8-}"
release_source_label_args=()
if [[ -n "$source_manifest_sha256" ]]; then
  release_source_label_args+=(
    --label "io.ds41rt.source-manifest.sha256=$source_manifest_sha256"
  )
fi
cd "$remote_dir"
python3 scripts/verify-sparkinfer-source.py \
  --source third_party/sparkinfer \
  --lock third_party/sparkinfer.lock.json \
  --require-no-python-cache
docker build \
  --build-arg DS41RT_ROLE=expert \
  --build-arg CUDA_ARCH=121 \
  --build-arg TARGET_PLATFORM=linux/arm64 \
  --build-arg DS41RT_SPARKINFER_COMMIT="$sparkinfer_commit" \
  -f docker/Dockerfile.dev \
  -t "$dev_image" .
mkdir -p .ds41rt-release-image
docker run --rm \
  --gpus all \
  --ipc=host \
  --ulimit memlock=-1:-1 \
  -e "DS41RT_RELEASE_EXL3_PAIRED_TP4=$exl3_paired_tp4" \
  -v "$remote_dir:/source:ro" \
  -v "$remote_dir/.ds41rt-release-image:/output" \
  "$dev_image" \
  /source/scripts/build-release-artifacts.sh /source expert 121 /output
docker build \
  "${release_source_label_args[@]}" \
  --build-arg DS41RT_ROLE=expert \
  --build-arg CUDA_ARCH=121 \
  --build-arg DS41RT_ENGINE_COMMIT="$engine_commit" \
  --build-arg DS41RT_SPARKINFER_COMMIT="$sparkinfer_commit" \
  --build-arg DS41RT_RELEASE_VERSION="$release_version" \
  -f docker/Dockerfile.release \
  -t "$inference_image" .
REMOTE
verify_remote_source_manifest

echo "== exporting release binaries =="
mkdir -p "$repo_root/dist/coordinator" "$repo_root/dist/spark-expert"
find "$repo_root/dist/coordinator" "$repo_root/dist/spark-expert" \
  -mindepth 1 -delete
coordinator_container="$(docker create "$COORDINATOR_DOCKER_INFERENCE")"
trap 'docker rm -f "$coordinator_container" >/dev/null 2>&1 || true' EXIT
docker cp "$coordinator_container:/opt/ds41rt/bin/ds41rt" "$repo_root/dist/coordinator/ds41rt"
docker cp "$coordinator_container:/opt/ds41rt/lib/libds41rt_native.so" "$repo_root/dist/coordinator/libds41rt_native.so"
docker cp "$coordinator_container:/opt/ds41rt/lib/exl3" "$repo_root/dist/coordinator/exl3"
docker cp "$coordinator_container:/opt/ds41rt/share/V41_EXPERT_AOT.json" "$repo_root/dist/coordinator/V41_EXPERT_AOT.json"
docker cp "$coordinator_container:/opt/ds41rt/share/V41_FP8_AOT.json" "$repo_root/dist/coordinator/V41_FP8_AOT.json"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/THIRD_PARTY_NOTICES.md" \
  "$repo_root/dist/coordinator/THIRD_PARTY_NOTICES.md"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/SPARKINFER_PROVENANCE.json" \
  "$repo_root/dist/coordinator/SPARKINFER_PROVENANCE.json"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/licenses/sparkinfer/LICENSE" \
  "$repo_root/dist/coordinator/SPARKINFER_LICENSE"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/SPARKINFER_SHA256SUMS" \
  "$repo_root/dist/coordinator/SPARKINFER_SHA256SUMS"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/XGRAMMAR_PROVENANCE.json" \
  "$repo_root/dist/coordinator/XGRAMMAR_PROVENANCE.json"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/licenses/xgrammar/LICENSE" \
  "$repo_root/dist/coordinator/XGRAMMAR_LICENSE"
docker cp \
  "$coordinator_container:/opt/ds41rt/share/XGRAMMAR_SHA256SUMS" \
  "$repo_root/dist/coordinator/XGRAMMAR_SHA256SUMS"
docker rm "$coordinator_container" >/dev/null
trap - EXIT

ssh -o BatchMode=yes "$seed_host" bash -s -- \
  "$SPARK_EXPERT_DOCKER_INFERENCE" "$remote_dir/dist/spark-expert" <<'REMOTE'
set -euo pipefail
image="$1"
destination="$2"
mkdir -p "$destination"
find "$destination" -mindepth 1 -delete
container="$(docker create "$image")"
trap 'docker rm -f "$container" >/dev/null 2>&1 || true' EXIT
docker cp "$container:/opt/ds41rt/bin/ds41rt" "$destination/ds41rt"
docker cp "$container:/opt/ds41rt/lib/libds41rt_native.so" "$destination/libds41rt_native.so"
docker cp "$container:/opt/ds41rt/lib/exl3" "$destination/exl3"
docker cp "$container:/opt/ds41rt/share/V41_EXPERT_AOT.json" "$destination/V41_EXPERT_AOT.json"
docker cp "$container:/opt/ds41rt/share/V41_FP8_AOT.json" "$destination/V41_FP8_AOT.json"
docker cp \
  "$container:/opt/ds41rt/share/THIRD_PARTY_NOTICES.md" \
  "$destination/THIRD_PARTY_NOTICES.md"
docker cp \
  "$container:/opt/ds41rt/share/SPARKINFER_PROVENANCE.json" \
  "$destination/SPARKINFER_PROVENANCE.json"
docker cp \
  "$container:/opt/ds41rt/share/licenses/sparkinfer/LICENSE" \
  "$destination/SPARKINFER_LICENSE"
docker cp \
  "$container:/opt/ds41rt/share/SPARKINFER_SHA256SUMS" \
  "$destination/SPARKINFER_SHA256SUMS"
docker cp \
  "$container:/opt/ds41rt/share/XGRAMMAR_PROVENANCE.json" \
  "$destination/XGRAMMAR_PROVENANCE.json"
docker cp \
  "$container:/opt/ds41rt/share/licenses/xgrammar/LICENSE" \
  "$destination/XGRAMMAR_LICENSE"
docker cp \
  "$container:/opt/ds41rt/share/XGRAMMAR_SHA256SUMS" \
  "$destination/XGRAMMAR_SHA256SUMS"
docker rm "$container" >/dev/null
trap - EXIT
REMOTE
release_sync --delete \
  "$seed_host:$remote_dir/dist/spark-expert/" \
  "$repo_root/dist/spark-expert/"
dist_source_manifest=()
if [[ -n "$source_manifest" ]]; then
  install -m 0644 "$source_manifest" "$repo_root/dist/SOURCE_SHA256SUMS"
  dist_source_manifest+=(SOURCE_SHA256SUMS)
fi
for role in coordinator spark-expert; do
  python3 "$repo_root/scripts/sparkinfer-release-provenance.py" \
    --source "$repo_root/third_party/sparkinfer" \
    --lock "$repo_root/third_party/sparkinfer.lock.json" \
    --license "$repo_root/dist/$role/SPARKINFER_LICENSE" \
    --notices "$repo_root/dist/$role/THIRD_PARTY_NOTICES.md" \
    --verify "$repo_root/dist/$role/SPARKINFER_PROVENANCE.json"
  (
    python3 "$repo_root/python/tools/package_v41_exl3_aot.py" verify --package "$repo_root/dist/$role/exl3" --sparkinfer-revision "$sparkinfer_commit"
    cd "$repo_root/dist/$role"
    sha256sum -c SPARKINFER_SHA256SUMS
    sha256sum -c XGRAMMAR_SHA256SUMS
  )
done
(
  cd "$repo_root/dist"
  sha256sum \
    coordinator/ds41rt coordinator/libds41rt_native.so coordinator/exl3/manifest.json coordinator/V41_EXPERT_AOT.json coordinator/V41_FP8_AOT.json \
    coordinator/THIRD_PARTY_NOTICES.md \
    coordinator/SPARKINFER_PROVENANCE.json \
    coordinator/SPARKINFER_LICENSE \
    coordinator/SPARKINFER_SHA256SUMS \
    coordinator/XGRAMMAR_PROVENANCE.json \
    coordinator/XGRAMMAR_LICENSE \
    coordinator/XGRAMMAR_SHA256SUMS \
    spark-expert/ds41rt spark-expert/libds41rt_native.so spark-expert/exl3/manifest.json spark-expert/V41_EXPERT_AOT.json spark-expert/V41_FP8_AOT.json \
    spark-expert/THIRD_PARTY_NOTICES.md \
    spark-expert/SPARKINFER_PROVENANCE.json \
    spark-expert/SPARKINFER_LICENSE \
    spark-expert/SPARKINFER_SHA256SUMS \
    spark-expert/XGRAMMAR_PROVENANCE.json \
    spark-expert/XGRAMMAR_LICENSE \
    spark-expert/XGRAMMAR_SHA256SUMS \
    "${dist_source_manifest[@]}" >SHA256SUMS
  sha256sum -c SHA256SUMS
)
verify_local_source_manifest
verify_remote_source_manifest

echo "== distributing fresh Spark inference image =="
for host in "${RELEASE_BUILD_HOSTS[@]:1}"; do
  # A stopped expert container can still reference the prior image ID. Force
  # removal only untags that image while preserving the referenced layers, so
  # ensure_image cannot mistake the stale tag for the fresh seed image.
  ssh -o BatchMode=yes "$host" "docker image rm --force '$SPARK_EXPERT_DOCKER_INFERENCE' >/dev/null 2>&1 || true"
done
rdmapipe_ready=1
for host in "${RELEASE_BUILD_HOSTS[@]}"; do
  if ! ssh -o BatchMode=yes "$host" "command -v rdmapipe >/dev/null 2>&1"; then
    rdmapipe_ready=0
    break
  fi
done
if ((rdmapipe_ready)); then
  echo "== concurrently distributing Spark image over RDMA =="
  image_copy_pids=()
  image_copy_hosts=()
  printf -v spark_image_quoted '%q' "$SPARK_EXPERT_DOCKER_INFERENCE"
  for host in "${RELEASE_BUILD_HOSTS[@]:1}"; do
    (
      set -o pipefail
      echo "== RDMA image copy $seed_host -> $host =="
      ssh -o BatchMode=yes "$seed_host" \
        "set -o pipefail; docker image save $spark_image_quoted | rdmapipe --send" |
        ssh -o BatchMode=yes "$host" \
          "set -o pipefail; rdmapipe --recv | docker image load"
      echo "== RDMA image copy $seed_host -> $host complete =="
    ) &
    image_copy_pids+=("$!")
    image_copy_hosts+=("$host")
  done
  image_copy_failed=0
  for index in "${!image_copy_pids[@]}"; do
    if ! wait "${image_copy_pids[$index]}"; then
      echo "RDMA image copy to ${image_copy_hosts[$index]} failed" >&2
      image_copy_failed=1
    fi
  done
  ((image_copy_failed == 0)) || release_die "concurrent RDMA Spark image distribution failed"
else
  echo "== rdmapipe unavailable on one or more Sparks; using serial netcat image distribution =="
  DS41RT_SPARK_HOSTS="$hosts_csv" \
  DS41RT_SPARK_IMAGE="$SPARK_EXPERT_DOCKER_INFERENCE" \
  DS41RT_SPARK_IMAGE_SEED_HOST="$seed_host" \
  DS41RT_SPARK_IMAGE_COPY_METHOD=spark-netcat \
  DS41RT_SPARK_IMAGE_ONLY=1 \
  DS41RT_SPARK_SKIP_STAGE=1 \
  "$repo_root/scripts/phase0-spark-tcp-bench.sh"
fi

coordinator_revision="$(
  docker image inspect -f '{{index .Config.Labels "org.opencontainers.image.revision"}}' \
    "$COORDINATOR_DOCKER_INFERENCE"
)"
[[ "$coordinator_revision" == "$engine_commit" ]] || release_die "coordinator image revision mismatch"
coordinator_version="$(
  docker image inspect -f '{{index .Config.Labels "org.opencontainers.image.version"}}' \
    "$COORDINATOR_DOCKER_INFERENCE"
)"
[[ "$coordinator_version" == "$release_version" ]] || release_die "coordinator image version mismatch"
coordinator_sparkinfer_revision="$(
  docker image inspect -f '{{index .Config.Labels "io.ds41rt.sparkinfer.revision"}}' \
    "$COORDINATOR_DOCKER_INFERENCE"
)"
[[ "$coordinator_sparkinfer_revision" == "$sparkinfer_commit" ]] ||
  release_die "coordinator image SparkInfer revision mismatch"
if [[ -n "$source_manifest_sha256" ]]; then
  coordinator_source_manifest="$(
    docker image inspect -f '{{index .Config.Labels "io.ds41rt.source-manifest.sha256"}}' \
      "$COORDINATOR_DOCKER_INFERENCE"
  )"
  [[ "$coordinator_source_manifest" == "$source_manifest_sha256" ]] ||
    release_die "coordinator image source manifest mismatch"
fi
for host in "${RELEASE_BUILD_HOSTS[@]}"; do
  revision="$(
    ssh -o BatchMode=yes "$host" \
      "docker image inspect -f '{{index .Config.Labels \"org.opencontainers.image.revision\"}}' '$SPARK_EXPERT_DOCKER_INFERENCE'"
  )"
  [[ "$revision" == "$engine_commit" ]] || release_die "$host Spark image revision mismatch: $revision"
  spark_version="$(
    ssh -o BatchMode=yes "$host" \
      "docker image inspect -f '{{index .Config.Labels \"org.opencontainers.image.version\"}}' '$SPARK_EXPERT_DOCKER_INFERENCE'"
  )"
  [[ "$spark_version" == "$release_version" ]] ||
    release_die "$host Spark image version mismatch: $spark_version"
  spark_sparkinfer_revision="$(
    ssh -o BatchMode=yes "$host" \
      "docker image inspect -f '{{index .Config.Labels \"io.ds41rt.sparkinfer.revision\"}}' '$SPARK_EXPERT_DOCKER_INFERENCE'"
  )"
  [[ "$spark_sparkinfer_revision" == "$sparkinfer_commit" ]] ||
    release_die "$host Spark image SparkInfer revision mismatch: $spark_sparkinfer_revision"
  if [[ -n "$source_manifest_sha256" ]]; then
    spark_source_manifest="$(
      ssh -o BatchMode=yes "$host" \
        "docker image inspect -f '{{index .Config.Labels \"io.ds41rt.source-manifest.sha256\"}}' '$SPARK_EXPERT_DOCKER_INFERENCE'"
    )"
    [[ "$spark_source_manifest" == "$source_manifest_sha256" ]] ||
      release_die "$host Spark image source manifest mismatch: $spark_source_manifest"
  fi
done

echo "Build complete."
echo "  revision:    $engine_commit"
echo "  SparkInfer:  $sparkinfer_commit"
if [[ -n "$source_manifest_sha256" ]]; then
  echo "  source:      $source_manifest_sha256"
fi
echo "  coordinator: $COORDINATOR_DOCKER_INFERENCE"
echo "  spark:       $SPARK_EXPERT_DOCKER_INFERENCE"
echo "  artifacts:   $repo_root/dist"
