[workspace]
resolver = "2"
members = [
  "crates/ds41rt-api",
  "crates/ds41rt-core",
  "crates/ds41rt-daemon",
  "crates/ds41rt-ffi",
  "crates/ds41rt-loader",
  "crates/ds41rt-transport",
    "crates/ds41rt-hostcache",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/tpurtell/ds41rt"

[workspace.dependencies]
anyhow = "1"
async-stream = "0.3"
axum = { version = "0.7", features = ["macros", "ws"] }
bincode = "1.3"
bytes = "1"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
io-uring = "0.7"
image = { version = "0.25.10", default-features = false, features = ["png", "webp", "gif"] }
turbojpeg = { version = "1.5.1", default-features = false, features = ["cmake", "require-simd"] }
libc = "0.2"
libloading = "0.8"
pyo3 = { version = "0.22", features = ["auto-initialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.10"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tokenizers = { version = "0.23.1", default-features = false, features = ["fancy-regex"] }
uuid = { version = "1", features = ["v4", "serde"] }
