#!/usr/bin/env python3
"""Assemble the v10 TP3 campaign manifests and docs from canonical sources.

v10 reporting has two stages:

  1. Each lane writes its own manifest next to its raw evidence (for the native
     arm, `runs/v10-native-tp3ep1/manifest.json`). That lane manifest is the
     durable record: raw paths, measured values, limitations and provenance.
  2. This bootstrap assembles the published campaign documents from those
     canonical manifests:

       docs/release-v10-tp3-official-1x-3spark.md
       docs/release-v10-tp3-exl3-compact-1x-3spark.md
       docs/release-v10-tp3-campaign-status.md

This script does not invent measurements and never launches anything; it only
writes manifests and invokes the CPU-only renderer.

A lane that has not been measured is emitted as an explicit PRE-MEASUREMENT
BOOTSTRAP manifest (`bootstrap_only: true`) with every family pending. This
script will never overwrite a canonical manifest that already carries raw
evidence, and it will not overwrite a committed measured report whose raw
evidence is absent from this checkout, so re-running it cannot erase a
measurement. Re-run it after a lane publishes its manifest and the same
documents carry the measured values.

Usage:
  runs/v10-tp3/generate-docs.py [--check]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]
HERE = pathlib.Path(__file__).resolve().parent
RENDERER = REPO / "scripts" / "render-ds41-v10-tp3-reports.py"
EXPECTED_COUNTS = REPO / "runs" / "v10-exl3-tp3" / "expected-counts.json"

STATUS = "NOT EXECUTED - pending raw manifests; no performance, memory, quality or readiness claim"
BOOTSTRAP_ONLY = (
    "PRE-MEASUREMENT BOOTSTRAP: generated by runs/v10-tp3/generate-docs.py before "
    "this lane wrote its own measured manifest. No performance, memory, quality or "
    "readiness claim. This file must never replace a canonical manifest that "
    "carries raw evidence."
)
# The renderer stamps each report with its render time; normalize it away before
# comparing content so an untouched report keeps its recorded timestamp.
GENERATED_RE = re.compile(r"^- Generated \(UTC\): .*$", re.MULTILINE)

# Canonical lane manifests, with the package their relative raw paths resolve
# against. The lane copy lives with the evidence and wins when present; the copy
# under runs/v10-tp3/ is the tracked publication record and is preserved as-is
# when the lane copy is not in this checkout.
LANE_MANIFESTS = {
    "v10-native-tp3ep1": (
        REPO / "runs" / "v10-native-tp3ep1" / "manifest.json",
        "runs/v10-native-tp3ep1",
    ),
}
# Per-arm expected-counts document, so a lane reconciles against its own.
EXPECTED_COUNTS_BY_ARM = {
    "v10-native-tp3ep1": REPO / "runs" / "v10-native-tp3ep1" / "expected-counts.json",
    "v10-exl3-compact-tp3": EXPECTED_COUNTS,
}

ARMS = (
    {
        "id": "v10-native-tp3ep1",
        "doc": "docs/release-v10-tp3-official-1x-3spark.md",
        "title": "DS41RT v10 TP3 official native 1x / 3-Spark: performance and qualification",
        "arm": {
            "id": "v10-native-tp3ep1",
            "quant": "official",
            "topology": "TP3xEP1",
            "topology_form": "explicit",
            "rtx": 1,
            "sparks": 3,
            "config_path": "examples/configs/tp3ep1-native.config",
            "comparison_group": "v10-1rtx-3spark",
            "resident_bytes_per_rank": 2406481920,
            "remote_layers": 35,
            "worker_allocated_layers": None,
            "weight_note": (
                "TP3 per-rank shard is the exact 2304/3 = 768-column slice, 2,406,481,920 B. "
                "Five RTX-local layers leave 35 remote: 35 x 2,406,481,920 = 84,226,867,200 B, "
                "inside the 109,119,320,064 B tested fleet floor by 24,892,452,864 B. "
                "Admission arithmetic only, not a runtime-fit claim."
            ),
            "ceiling": {
                "memory_reservation": None,
                "kv_pool_size": None,
                "prefill_batch_tokens": None,
                "note": "Uncapped native arm; no 32 GiB simulation applies.",
            },
            "runtime_flags": {
                "spark_count": 3, "spark_tp": 3, "spark_ep": 1,
                "rtx_expert_layers": 5, "remote_dispatch_layers": 35,
                "expert_format": "native", "dspark": "on",
            },
            "raw": {},
            "warmup": "one shape warmup, excluded from the ledger",
            "repeats": 3,
            "notes": "Not launched: the v10 image pair is not published, so no raw evidence exists and every family is PENDING.",
            "failures": [],
        },
    },
    {
        "id": "v10-exl3-compact-tp3",
        "doc": "docs/release-v10-tp3-exl3-compact-1x-3spark.md",
        "title": "DS41RT v10 compact EXL3 TP3 1x / 3-Spark: performance and qualification",
        "arm": {
            "id": "v10-exl3-compact-tp3",
            "quant": "exl3",
            "topology": "TP3",
            "topology_form": "implicit",
            "rtx": 1,
            "sparks": 3,
            "config_path": "examples/configs/exl3-compact-tp3.config",
            "comparison_group": "v10-1rtx-3spark",
            "resident_bytes_per_rank": None,
            "remote_layers": None,
            "worker_allocated_layers": None,
            "weight_note": (
                "Compact EXL3 TP3 is the implicit layout (SPARK_COUNT=3 with no "
                "SPARK_TP/SPARK_EP); each rank serves the 2304/3 = 768-column shard from "
                "non-paired disjoint k34-family packages. Resident bytes are not yet captured "
                "and are not inferred from the native arm."
            ),
            "ceiling": {
                "memory_reservation": "32GiB",
                "memory_reservation_bytes": 34359738368,
                "kv_pool_size": "2GiB",
                "kv_pool_size_bytes": 2147483648,
                "prefill_batch_tokens": 256,
                "evidence": None,
                "note": (
                    "Declared ceiling from examples/configs/exl3-compact-tp3.config. The resolved "
                    "reservation, occupancy and KV figures must be captured from the service at "
                    "launch; the declared values are not a proven fit."
                ),
            },
            "runtime_flags": {
                "spark_count": 3, "spark_tp": "implicit (count = TP)", "spark_ep": 1,
                "expert_format": "exl3", "exl3_family": "k34",
                "memory_reservation": "32GiB", "kv_pool_size": "2GiB",
                "prefill_batch_tokens": 256, "dspark": "on",
            },
            "raw": {},
            "warmup": "one shape warmup, excluded from the ledger",
            "repeats": 3,
            "notes": (
                "Not launched: the v10 image pair is not published and the k34 "
                "tp3-rank{0,1,2} packages must be present in the Spark image. Every family is PENDING."
            ),
            "failures": [],
        },
    },
)


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def base_manifest() -> dict:
    return {
        "release": "v10",
        "checkpoint": {
            "model_id": "deepseek-ai/DeepSeek-V4.1-Flash",
            "revision": "dba1be0a40aa45a94ad051997016db3960a90277",
            "quant": "official",
        },
        "accounting": {
            "repeats": 3,
            "prefill_warmups": 1,
            "tool_eval_runs": 3,
            "note": ("One shape warmup then three timed samples per cell; retained uses three "
                     "repeats per isolated context. Expected counts are re-derived from the "
                     "live harness scripts at check/render time."),
        },
        "report_status": STATUS,
    }


def arm_with_config(entry: dict) -> dict:
    """The entry's arm with its config digest filled in from the live file."""
    arm = json.loads(json.dumps(entry["arm"]))
    config = REPO / arm["config_path"]
    arm["config_sha256"] = sha256(config)
    arm["notes"] = (arm.get("notes") or "") + (
        f" config_sha256 is the current committed hash of {arm['config_path']} "
        "(re-verify at freeze).")
    return arm


def bootstrap_manifest(entry: dict) -> dict:
    """A clearly labelled pre-measurement manifest for an unmeasured arm."""
    manifest = base_manifest()
    arm = arm_with_config(entry)
    arm["bootstrap_only"] = True
    arm["bootstrap_note"] = BOOTSTRAP_ONLY
    manifest["arms"] = [arm]
    manifest["report_title"] = entry["title"]
    return manifest


def evidence_package(document: dict) -> str | None:
    for arm in document.get("arms") or []:
        if arm.get("evidence_package"):
            return arm["evidence_package"]
    return None


# Publication metadata is owned by this generator, not by a lane's manifest
# writer: a lane that regenerates its manifest drops or resets these keys, so
# they are overlaid from the tracked canonical record whenever it has them.
PUBLICATION_KEYS = ("report_status", "report_class", "harness_provenance")
ARM_PUBLICATION_KEYS = ("evidence_package", "measurement_provenance", "limitations")


def overlay_publication(document: dict, canonical: dict) -> dict:
    """Carry publication metadata from the tracked canonical record onto a lane
    manifest, without touching the lane's measured values, raw paths or config."""
    for key in PUBLICATION_KEYS:
        if canonical.get(key) is not None:
            document[key] = canonical[key]
    canonical_arms = {arm.get("id"): arm for arm in canonical.get("arms") or []}
    for arm in document.get("arms") or []:
        source = canonical_arms.get(arm.get("id"))
        if not source:
            continue
        for key in ARM_PUBLICATION_KEYS:
            if source.get(key) is not None:
                arm[key] = source[key]
    return document


def canonical_for(entry: dict) -> tuple[dict, str, str]:
    """Return (document, package, origin) for one arm.

    Preference: the lane's own measured manifest, then the tracked canonical
    manifest (preserved verbatim, never reset), then a labelled bootstrap. A
    lane manifest is overlaid with the tracked publication metadata so a lane
    regeneration cannot erase the limitations attached to the numbers.
    """
    lane = LANE_MANIFESTS.get(entry["id"])
    tracked = HERE / f"{entry['id']}-manifest.json"
    if lane and lane[0].is_file():
        document = json.loads(lane[0].read_text())
        if tracked.is_file():
            document = overlay_publication(document, json.loads(tracked.read_text()))
        return document, lane[1], "measured"
    if tracked.is_file():
        document = json.loads(tracked.read_text())
        return document, evidence_package(document) or "runs/v10-tp3", "canonical"
    return bootstrap_manifest(entry), "runs/v10-tp3", "bootstrap"


def as_paths(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [str(item) for item in value]
    return []


def evidence_available(document: dict) -> bool:
    """True when every raw artifact a measured manifest names is present here."""
    for arm in document.get("arms") or []:
        raw = arm.get("raw") or {}
        if not raw:
            continue
        package = arm.get("evidence_package") or "runs/v10-tp3"
        for paths in raw.values():
            for relative in as_paths(paths):
                if not (REPO / package / relative).is_file():
                    return False
        summaries = (arm.get("tool_eval") or {}).get("summaries")
        if summaries and not (REPO / package / summaries).is_file():
            return False
    return True


def campaign_status(documents: dict) -> str:
    measured = []
    for entry in ARMS:
        document = documents[f"runs/v10-tp3/{entry['id']}-manifest.json"]
        for arm in document.get("arms") or []:
            if arm.get("raw"):
                measured.append(entry["id"])
    if not measured:
        return STATUS
    return ("INCOMPLETE / INFORMATIONAL - measured arm(s): " + ", ".join(measured)
            + "; every number is conditional on that arm's attached limitations and "
            "none of it is a formal qualification")


def build() -> tuple[dict, list[tuple[str, str, str]]]:
    documents: dict[str, dict] = {}
    render_jobs: list[tuple[str, str, str]] = []
    canonical: dict[str, dict] = {}
    for entry in ARMS:
        document, package, _origin = canonical_for(entry)
        manifest_rel = f"runs/v10-tp3/{entry['id']}-manifest.json"
        documents[manifest_rel] = document
        canonical[entry["id"]] = document
        render_jobs.append((entry["doc"], manifest_rel, package))

    campaign = base_manifest()
    # Preserve the committed arm record for any arm that is still unmeasured, so
    # this bootstrap cannot rewrite an arm it did not measure (EXL3 data).
    existing_arms: dict[str, dict] = {}
    campaign_path = HERE / "campaign-manifest.json"
    if campaign_path.is_file():
        existing = json.loads(campaign_path.read_text())
        existing_arms = {arm.get("id"): arm for arm in existing.get("arms") or []}
    campaign_arms = []
    for entry in ARMS:
        measured_arm = canonical[entry["id"]]["arms"][0]
        if not (measured_arm.get("raw") or {}) and entry["id"] in existing_arms:
            campaign_arms.append(json.loads(json.dumps(existing_arms[entry["id"]])))
        else:
            campaign_arms.append(json.loads(json.dumps(measured_arm)))
    campaign["arms"] = campaign_arms
    campaign["report_status"] = campaign_status(documents)
    for key in ("report_class", "harness_provenance"):
        for entry in ARMS:
            value = canonical[entry["id"]].get(key)
            if value is not None:
                campaign[key] = value
                break
    campaign["report_title"] = "DS41RT v10 TP3 campaign status: native TP3EP1 and compact EXL3 TP3"
    documents["runs/v10-tp3/campaign-manifest.json"] = campaign
    render_jobs.append(("docs/release-v10-tp3-campaign-status.md",
                        "runs/v10-tp3/campaign-manifest.json", "runs/v10-tp3"))
    return documents, render_jobs


def expected_counts_for(manifest_rel: str) -> pathlib.Path | None:
    stem = pathlib.Path(manifest_rel).name
    for arm_id, path in EXPECTED_COUNTS_BY_ARM.items():
        if stem == f"{arm_id}-manifest.json":
            return path if path.is_file() else EXPECTED_COUNTS
    return EXPECTED_COUNTS if EXPECTED_COUNTS.is_file() else None


def render_text(manifest_rel: str, package: str) -> tuple[str | None, str]:
    """Render one document to a temp file; return (text, error)."""
    command = [sys.executable, str(RENDERER),
               "--manifest", str(REPO / manifest_rel),
               "--package", str(REPO / package)]
    counts = expected_counts_for(manifest_rel)
    if counts is not None:
        command += ["--expected-counts", str(counts)]
    with tempfile.TemporaryDirectory() as directory:
        output = pathlib.Path(directory) / "report.md"
        command += ["--output", str(output)]
        result = subprocess.run(command, cwd=REPO, capture_output=True, text=True)
        if result.returncode != 0 or not output.is_file():
            return None, (result.stderr or result.stdout or "renderer failed").strip()
        return output.read_text(), ""


def normalize(text: str) -> str:
    return GENERATED_RE.sub("- Generated (UTC): <normalized>", text)


def write(documents: dict, render_jobs: list[tuple[str, str, str]], check: bool) -> int:
    problems = []
    for relative, document in documents.items():
        path = REPO / relative
        text = json.dumps(document, indent=2) + "\n"
        if not path.is_file() or path.read_text() != text:
            if check:
                problems.append(f"{relative} is stale")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
                print(f"wrote {relative}")

    for doc_rel, manifest_rel, package in render_jobs:
        committed = REPO / doc_rel
        document = documents[manifest_rel]
        measured = any((arm.get("raw") or {}) for arm in document.get("arms") or [])
        if not measured and committed.is_file():
            # An unmeasured arm keeps its committed bootstrap report untouched:
            # this bootstrap does not re-render placeholder documents.
            print(f"kept {doc_rel}: arm is unmeasured; committed bootstrap report preserved")
            continue
        if not evidence_available(document) and committed.is_file():
            print(f"kept {doc_rel}: raw evidence for its measured arm is not in this "
                  "checkout, so the committed report is not re-rendered")
            continue
        rendered, error = render_text(manifest_rel, package)
        if rendered is None:
            problems.append(f"{doc_rel}: render failed: {error}")
            continue
        if committed.is_file() and normalize(committed.read_text()) == normalize(rendered):
            continue  # current: leave the committed timestamp untouched
        if check:
            problems.append(f"{doc_rel} is stale")
            continue
        committed.parent.mkdir(parents=True, exist_ok=True)
        committed.write_text(rendered)
        print(f"wrote {doc_rel}")

    for problem in problems:
        print(f"PROBLEM {problem}", file=sys.stderr)
    return 1 if problems else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Do not write; report stale manifests/docs.")
    args = parser.parse_args()
    documents, render_jobs = build()
    return write(documents, render_jobs, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
